version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cliply_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cliply}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cliply_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-cliply_development}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cliply} -d ${POSTGRES_DB:-cliply_development}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cliply_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cliply_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-cliply}:${POSTGRES_PASSWORD:-cliply_dev_password}@postgres:5432/${POSTGRES_DB:-cliply_development}
      REDIS_URL: redis://redis:6379/0
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

  sidekiq:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cliply_sidekiq
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-cliply}:${POSTGRES_PASSWORD:-cliply_dev_password}@postgres:5432/${POSTGRES_DB:-cliply_development}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
    command: bundle exec sidekiq

volumes:
  postgres_data:
  redis_data:
  bundle_cache: